### ISSUE TITLE
Filter bei "Load File" funktionieren nicht ordnungsgemäß

### ISSUE THREAD

**Issue by Asiimate** [cforler/SimpleComputerEmulator#1]
Ein vorher abgespeichertes Programm kann über die Schaltfläche "Load File" nicht direkt wieder geladen werden, ohne vorher "All Files" auszuwählen. Die Selektierung beziehungsweise Speicherung der Dateien scheint keine genaue Dateibezeichnung zu besitzen und somit kann diese nicht angezeigt werden.

**Comment by cforler** [comment]
Damit ein abgespeichertes Programm direkt wieder geladen werden kann, muss es auf ".txt" enden.
